# Generated by Django 5.2.11 on 2026-02-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='is_contacted',
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='pending', max_length=20),
        ),
    ]
